### ISSUE TITLE
[REQUEST] Progress bar for longer upload

### ISSUE THREAD

**Issue by princeHago** [ravindu1024/velocity#2]
Hi, 

first to all I want to thank you for this addons.

When i upload a bigger file, like an image base64, I would like to view a progress bar, can you add this feature?

Thanks in advance!

**Comment by ravindu1024** [comment]
Hi princHago,

You're very welcome.

I have already included a callback to report the upload status as a percentage of file size. You can use the following method:
```java
Velocity.upload("upload url").withProgressListener(new Velocity.ProgressListener()
            {
                @Override
                public void onFileProgress(int progress)
                {
                    
                }
            });
```
I didn't want to include a progress dialog within the library so that the user has the freedom to use any progress bar they like. I just report the progress percentage. Hope this helps.

**Comment by princeHago** [comment]
hi, thanks for your reply.

i modify my code introducing the following code, but it didn't work

```
Velocity.post(Constants.urlServer + urlServizio)
                .withFormData(nameValuePairs.get(0).getName(), nameValuePairs.get(0).getValue())
                .withProgressListener(new Velocity.ProgressListener()
                {
                    @Override
                    public void onFileProgress(int progress) {
                        Log.d(Constants.debug, "Velocity onFileProgress:" + progress);
                        if(!StringUtils.isNull(nameValuePairs.get(0).getName()).contains("txt")){
                            ((ProgressBarHUD)progressHUD).getSpinner().setProgress(progress);
                        }
                    }
                })
                .connect(new Velocity.ResponseListener()
                {.....
```

**Comment by ravindu1024** [comment]
Hi,
Are you trying to upload a file or make a post call? If you want to upload a file, you should use Velocity.upload() and then set the file path. The progress callback only works for uploading files, and not for regular post calls.

**Comment by princeHago** [comment]
i make a post call. as parameter i send an image encoded in base 64. why the progress callback works only for upload files?

**Comment by ravindu1024** [comment]
I see. Have a look at setupRequestBody() in [Request.java](https://github.com/ravindu1024/velocity/blob/master/velocity/src/main/java/com/rw/velocity/Request.java). I convert the form data into a single string and then write it into the OutputStream of  the http connection. I dont think I can add a progress callback to that. I'm open to suggestions :)
